"""Build the crypto_strategy_research.md from raw transcripts."""

import json
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

RAW = r"C:\Users\magli\Desktop\TradeEngine\docs\transcripts_raw.json"
OUT = r"C:\Users\magli\Desktop\TradeEngine\docs\crypto_strategy_research.md"

with open(RAW, "r", encoding="utf-8") as f:
    data = json.load(f)

total_words = sum(r["word_count"] for r in data["results"])
n_videos = len(data["results"])

lines = []


def w(text=""):
    lines.append(text)


w("# Crypto & AI Trading Strategy Research")
w("## Compiled from YouTube Video Transcripts")
w(f"### Date: 2026-04-12 | Videos: {n_videos} | Total Words: {total_words}")
w()
w("---")
w()
w("# PART 1: ACTIONABLE STRATEGY SUMMARIES")
w()

# ================================================================
# STRATEGY 1
# ================================================================
w("## Strategy 1: Bollinger Bands + RSI Mean Reversion")
w('**Source:** "Bollinger Band + RSI Trading Strategy That Actually Works" (pCmJ8wsAS_w)')
w()
w("### Strategy Type")
w("Mean reversion on any liquid asset (stocks, crypto, forex)")
w()
w("### Indicator Settings")
w("- Bollinger Bands: Length = 30, Standard Deviation = 2")
w("- RSI: Length = 13, Overbought = 75, Oversold = 25")
w()
w("### Entry Signals")
w("- LONG: Price closes below lower Bollinger Band AND RSI drops below 25")
w("- SHORT: Price closes above upper Bollinger Band AND RSI rises above 75")
w()
w("### Exit Signals")
w("- Exit when price returns to the middle Bollinger Band (the moving average)")
w()
w("### Risk Management")
w("- AVOID trading when Bollinger Bands are narrow/squeezed (sideways market)")
w("- Narrow bands followed by breakout = momentum move, NOT mean reversion")
w("- Look for RSI divergence as confirmation: price makes lower low but RSI makes higher low = strong reversal signal")
w()
w("### Key Parameters for Coding")
w("```")
w("bb_length: 30")
w("bb_std: 2")
w("rsi_length: 13")
w("rsi_overbought: 75")
w("rsi_oversold: 25")
w("exit_target: middle_bollinger_band (SMA)")
w("filter: skip_when_bb_bandwidth < threshold (squeeze detection)")
w("```")
w()

# ================================================================
# STRATEGY 2
# ================================================================
w("## Strategy 2: BB + RSI Backtested Across Markets (FreqTrade)")
w('**Source:** "I Tested RSI + Bollinger Bands Strategy in 2025" (j2ESnjhT2no)')
w()
w("### Strategy Type")
w("Mean reversion with FreqTrade hyperparameter optimization")
w()
w("### Indicator Settings (Default from video)")
w("- Bollinger Bands: default period with configurable std")
w("- RSI: standard with configurable overbought/oversold thresholds")
w()
w("### Entry Signals")
w("- LONG: Price crosses below lower Bollinger Band AND RSI crosses below oversold threshold")
w("- SHORT: Price crosses above upper Bollinger Band AND RSI crosses above overbought threshold")
w()
w("### Exit Signals")
w("- Exit LONG when price crosses middle Bollinger Band AND RSI above threshold")
w("- Exit SHORT when price crosses middle Bollinger Band AND RSI below threshold")
w()
w("### Backtest Results (CRITICAL FINDING)")
w("- CRYPTO: Strategy performed POORLY across ALL timeframes (1m to 1d)")
w("  - 1-day: Sharpe 12, profit only $70 (marginal)")
w("  - 4h: Sharpe -1.17, loss $370")
w("  - 1h: Sharpe -33, loss $3,000")
w("  - 15m: Sharpe -42, loss $1,800")
w("  - 5m: Sharpe -90, loss $2,000")
w("  - 1m: Sharpe -1000, loss $3,700")
w("- STOCKS: Mixed results, 1h and 15m slightly positive")
w("- FUTURES: 5m (Sharpe 8.69, +$300) and 1m (Sharpe 25, +$375) worked")
w("- Hyperparameter optimization provided only marginal improvement")
w()
w("### CONCLUSION: Simple BB+RSI is NOT reliable for crypto")
w("The raw BB+RSI mean reversion strategy does NOT work consistently on crypto markets.")
w("It needs additional filters (trend, ADX, volume) to be viable.")
w()

# ================================================================
# STRATEGY 3
# ================================================================
w("## Strategy 3: Advanced Mean Reversion with ADX + Multi-Timeframe RSI (FreqTrade)")
w('**Source:** "Mean Reversion Trading Strategy Explained & Backtested -- 179% Profit" (c9-SIpy3dEw)')
w()
w("### Strategy Type")
w("Mean reversion with trend filtering on 1H timeframe, optimized via FreqTrade")
w()
w("### Indicator Settings")
w("- Bollinger Bands: 20-period SMA, 2 standard deviations (1H chart)")
w("- RSI: Used on 4H timeframe as TREND FILTER (not entry signal)")
w("- ADX: Applied on both 1H and 4H timeframes")
w("- ATR: Used for dynamic stop-loss placement")
w()
w("### Entry Signals (LONG)")
w("1. 4H RSI > 55 (confirms bullish trend)")
w("2. ADX > 20 on 1H chart (sufficient trend strength)")
w("3. ADX > 25 on 4H chart (medium-term trend confirmed)")
w("4. Price closes below lower Bollinger Band on 1H (oversold)")
w("5. Enter on NEXT candle after all conditions met")
w()
w("### Entry Signals (SHORT)")
w("1. 4H RSI < 45 (confirms bearish trend)")
w("2. ADX > 20 on 1H chart")
w("3. ADX > 25 on 4H chart")
w("4. Price closes above upper Bollinger Band on 1H (overbought)")
w("5. Enter on NEXT candle")
w()
w("### Exit Signals")
w("- LONG exit: Price closes above upper Bollinger Band")
w("- SHORT exit: Price closes below lower Bollinger Band")
w()
w("### Risk Management")
w("- Stop Loss: Below signal candle low minus 4.5x ATR (for longs)")
w("- Stop Loss: Above signal candle high plus 4.5x ATR (for shorts)")
w()
w("### Backtest Results")
w("- Total profit: 179% on NEAR perpetual futures, 1H timeframe, 1 year")
w("- Market returned -66% in the same period")
w("- Max drawdown: 19.3%")
w("- Tested with 8-month in-sample / 4-month out-of-sample split")
w()
w("### Key Parameters for Coding")
w("```")
w("timeframe: 1H (trading), 4H (trend filter)")
w("bb_period: 20 (optimizable)")
w("bb_std: 2 (optimizable)")
w("htf_rsi_long_threshold: 55")
w("htf_rsi_short_threshold: 45")
w("adx_threshold_1h: 20")
w("adx_threshold_4h: 25")
w("atr_multiplier_stoploss: 4.5")
w("exit: opposite_bollinger_band")
w("```")
w()

# ================================================================
# STRATEGY 4
# ================================================================
w("## Strategy 4: AI/ML Sentiment-Driven Trading Bot (Lumibot + Alpaca)")
w('**Source:** "How to Code a AI Trading bot (so you can make $$$)" (c9OjEThuJjY)')
w()
w("### Strategy Type")
w("News sentiment analysis using FinBERT ML model, daily timeframe")
w()
w("### Architecture")
w("- Framework: Lumibot (Python trading framework)")
w("- Broker: Alpaca API (paper trading)")
w("- ML Model: FinBERT for financial sentiment analysis")
w("- Data: Alpaca News API, last 3 days of news")
w()
w("### Entry Signals")
w("- BUY: Sentiment is positive AND probability > 0.999 AND no existing position")
w("- SELL/SHORT: Sentiment is negative AND probability > 0.999 AND last trade was buy")
w()
w("### Position Sizing")
w("- cash_at_risk = 0.5 (50% of available cash per trade)")
w("- quantity = (cash * cash_at_risk) / last_price")
w()
w("### Risk Management")
w("- Bracket orders with:")
w("  - Take profit (long): +20% from entry")
w("  - Stop loss (long): -5% from entry")
w("  - Take profit (short): -20% from entry (price * 0.8)")
w("  - Stop loss (short): +5% from entry (price * 1.05)")
w()
w("### Backtest Results")
w("- 4-year backtest (2020-2023) on SPY")
w("- Cumulative return: 234.40%")
w("- Compound annual growth rate: 23.8%")
w("- Bot correctly short-sold during market downturns")
w("- Peak portfolio value: ~$537,500 (from $100K)")
w()
w("### Key Parameters for Coding")
w("```")
w("symbol: SPY (adaptable to crypto)")
w("sleep_time: 24H (daily trading)")
w("cash_at_risk: 0.5")
w("sentiment_model: FinBERT")
w("sentiment_threshold: 0.999 probability")
w("news_lookback: 3 days")
w("take_profit_long: 1.20 (20%)")
w("stop_loss_long: 0.95 (5%)")
w("take_profit_short: 0.80 (20%)")
w("stop_loss_short: 1.05 (5%)")
w("order_type: bracket")
w("```")
w()

# ================================================================
# STRATEGY 5
# ================================================================
w("## Strategy 5: RSI Crypto Trading Bot (Real-Time Websocket)")
w('**Source:** "Build a Real-Time Crypto Trading Bot in under 100 Lines" (GdlFhF6gjKo)')
w()
w("### Strategy Type")
w("RSI overbought/oversold on 1-minute candlesticks via Binance websocket")
w()
w("### Indicator Settings")
w("- RSI Period: 14 (default ta-lib)")
w("- Overbought threshold: 70")
w("- Oversold threshold: 30")
w("- Timeframe: 1-minute candles (real-time)")
w()
w("### Entry Signals")
w("- BUY: RSI crosses below 30 (oversold)")
w("- SELL: RSI crosses above 70 (overbought)")
w()
w("### Architecture")
w("- Data: Binance websocket stream (ethusdt@kline_1m)")
w("- Indicator: ta-lib RSI calculation on closing prices array")
w("- Execution: Binance API market orders")
w("- Position tracking: boolean in_position flag")
w()
w("### Key Parameters for Coding")
w("```")
w("symbol: ETHUSDT")
w("timeframe: 1m candles")
w("rsi_period: 14")
w("rsi_overbought: 70")
w("rsi_oversold: 30")
w("order_type: market")
w("data_source: websocket (binance)")
w("```")
w()

# ================================================================
# STRATEGY 6
# ================================================================
w("## Strategy 6: Dual Moving Average Crossover")
w('**Source:** "Algorithmic Trading Strategy Using Python" (SEQbb8w7VTw)')
w()
w("### Strategy Type")
w("Trend-following moving average crossover")
w()
w("### Indicator Settings")
w("- Short-term SMA: 30-day window")
w("- Long-term SMA: 100-day window")
w("- Applied to: Adjusted Close Price")
w()
w("### Entry Signals")
w("- BUY: 30-day SMA crosses ABOVE 100-day SMA (golden cross)")
w("- SELL: 30-day SMA crosses BELOW 100-day SMA (death cross)")
w()
w("### Key Parameters for Coding")
w("```")
w("sma_short: 30")
w("sma_long: 100")
w("price_field: adjusted_close")
w("signal: crossover detection")
w("```")
w()

# ================================================================
# SYNTHESIS
# ================================================================
w("---")
w()
w("# PART 2: SYNTHESIS -- WHAT TO IMPLEMENT FOR ATLAS LITE")
w()
w("## Recommended Strategy: Advanced Mean Reversion (Strategy 3)")
w("This is the most backtested and production-ready strategy from the research.")
w("It addresses the key failure of simple BB+RSI (Strategy 2 proved it fails on crypto)")
w("by adding crucial filters:")
w()
w("### Why Strategy 3 Wins")
w("1. Multi-timeframe confirmation (1H trade, 4H trend filter)")
w("2. ADX filter prevents trading in choppy/sideways markets")
w("3. RSI used as trend filter (not entry), avoiding false signals")
w("4. ATR-based dynamic stop loss adapts to volatility")
w("5. 179% profit vs -66% market, with only 19% max drawdown")
w("6. Tested with proper in-sample/out-of-sample methodology")
w()
w("### Implementation Parameters for ATLAS Lite")
w("```json")
w("{")
w('  "strategy_name": "mean_reversion_adx",')
w('  "timeframe_trade": "1H",')
w('  "timeframe_trend": "4H",')
w('  "bollinger_period": 20,')
w('  "bollinger_std": 2.0,')
w('  "rsi_trend_long": 55,')
w('  "rsi_trend_short": 45,')
w('  "adx_threshold_trade": 20,')
w('  "adx_threshold_trend": 25,')
w('  "atr_stop_multiplier": 4.5,')
w('  "exit_rule": "opposite_bollinger_band",')
w('  "coins": ["BTC/USD", "ETH/USD"],')
w('  "max_position_pct": 5,')
w('  "cash_reserve_pct": 20')
w("}")
w("```")
w()
w("### Secondary Strategy: Sentiment-Driven (Strategy 4)")
w("Could complement mean reversion as an additional signal layer:")
w("- Use FinBERT or similar model on crypto news")
w("- High-confidence sentiment (>99.9%) as trade filter")
w("- Bracket orders with 20% take-profit, 5% stop-loss")
w("- Daily timeframe to avoid noise")
w()
w("### What NOT to Implement")
w("- Simple BB+RSI without filters (Strategy 2 proves it loses money on crypto)")
w("- Pure RSI on 1-minute candles (too noisy, high fees eat profits)")
w("- Moving average crossover alone (too slow for crypto volatility)")
w()
w("---")
w()

# ================================================================
# FULL TRANSCRIPTS
# ================================================================
w("# PART 3: FULL TRANSCRIPTS")
w()

for r in data["results"]:
    w(f"## Transcript: {r['title']}")
    w(f"**Video ID:** {r['video_id']} | **Words:** {r['word_count']}")
    w(f"**URL:** https://www.youtube.com/watch?v={r['video_id']}")
    w()
    w("```")
    w(r["transcript"])
    w("```")
    w()
    w("---")
    w()

content = "\n".join(lines)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Written {len(content):,} chars to {OUT}")
print(f"Document contains {len(lines)} lines")
